# datasets
datasets: GraspNet
data_dir: /data1/dengxuxiang/datasets/GraspNetPointClouds
tgt_multi_view: False
# src_domain: Synthetic
# tgt_domain: target_train.txt    建议通过auto run里面的任务来输入

# Backbone
model_name: VIT-B

# FixMatch
fixmatch: False
use_amp: True

# Optimizer related
lr: 3e-6
weight_decay: 5e-4
momentum: 0.9
label_smoothing: 0.1
l_batch_size: 32
u_batch_size: 32

# Loss related
lambda1: 0.25
lambda2: 0.1
lambda3: 0.025

# scheduler related
scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
multiple_lr_classifier: 1000

# Training related
n_iter_per_epoch: 200
n_epoch: 100

# Others
seed: 42
num_workers: 4
